### ISSUE TITLE
32 bit powershell support? 

### ISSUE THREAD

**Issue by SamuelmAsh** [iricigor/FIFA2018#23]
Morning mate, i am trying to create a monitoring item for todays scores using your awesome ps wrapper, however our monitoring platform only runs 32bit powershell. Any plans to make this compatible with install-package in 32 bit?

**Comment by iricigor** [comment]
Hi, can you give me some error description or screenshot of an issue you are having? I tried running the module inside 32-bit edition, and it worked fine. Or, is it a problem with installing it there?

**Comment by SamuelmAsh** [comment]
Nevermind, this was enitrely user error on my end :P
